"""Unit tests for gimme_aws_creds"""
import hashlib
import json
import sys
import unittest
from contextlib import contextmanager
from io import StringIO
from unittest.mock import patch
from urllib.parse import quote

import requests
import responses
from fido2.attestation import PackedAttestation
from fido2.ctap2 import AttestationObject, AuthenticatorData, AttestedCredentialData

from gimme_aws_creds import errors, ui
from gimme_aws_creds.okta_identity_engine import OktaIdentityEngine


class TestOktaIdentityEngineClient(unittest.TestCase):
    """Class to test Okta Client Class.
       Mock is used to mock external calls"""

    @contextmanager
    def captured_output(self):
        """Capture StdErr and StdOut"""
        new_out, new_err = StringIO(), StringIO()
        old_out, old_err = sys.stdout, sys.stderr
        try:
            sys.stdout, sys.stderr = new_out, new_err
            yield sys.stdout, sys.stderr
        finally:
            sys.stdout, sys.stderr = old_out, old_err

    def setUp(self):
        """Set up for the unit tests"""
        self.okta_org_url = 'https://example-oie.okta.com'
        self.server_embed_link = 'https://example-oie.okta.com/home/foo/bar/baz'
        self.gimme_creds_server = 'https://localhost:8443'
        self.login_url = 'https://localhost:8443/login?stateToken=00Wf8xZJ79mSoTYnJqXbvRegT8QB1EX1IBVk1TU7KI'
        self.client_id = '00Wf8xZJ79mSoTY'
        self.client = self.setUp_client(self.okta_org_url, self.client_id, False)
        self.device_code = '7ba11a95-e564-499a-b9b0-69c01ac6bbf9'
        self.username = 'test@example.com'

        self.device_response = {
            "device_code": "7ba11a95-e564-499a-b9b0-69c01ac6bbf9",
            "user_code": "ZWGQJTMP",
            "verification_uri": "https://example-oie.okta.com/activate",
            "verification_uri_complete": "https://example-oie.okta.com/activate?user_code=ZWGQJTMP",
            "expires_in": 600,
            "interval": 5
        }

        self.token_response = {
            "token_type": "Bearer",
            "expires_in": 3600,
            "access_token": "eyJraWQiOiI0YzRwMkxudmxkdHRSdW56UHN3VzN0d0tPYzVGNkpZN1c3U1l3OEoyaXRRIiwiYWxnIjoiUlMyNTYifQ.ewogICJ2ZXIiOiAxLAogICJqdGkiOiAiQVQudlZ3QU1uaWVoVkF4THlXY2dYQW5udXh0RzM3bjROdGpaemxxRzhiSFM5ZyIsCiAgImlzcyI6ICJodHRwczovL2V4YW1wbGUtb2llLm9rdGFwcmV2aWV3LmNvbSIsCiAgImF1ZCI6ICJodHRwczovL2V4YW1wbGUtb2llLm9rdGFwcmV2aWV3LmNvbSIsCiAgInN1YiI6ICJ0ZXN0QGV4YW1wbGUuY29tIiwKICAiaWF0IjogMTY4MDExMjA3NCwKICAiZXhwIjogMTY4MDExNTY3NCwKICAiY2lkIjogIjBvYTczNnBobmFlWU9xVVJKMWQ3IiwKICAidWlkIjogIjAwdTEwYzhudXNMTDlkcllyMWQ3IiwKICAic2NwIjogWwogICAgIm9wZW5pZCIsCiAgICAib2t0YS5hcHBzLnNzbyIKICBdLAogICJhdXRoX3RpbWUiOiAxNjgwMTEwODk1Cn0.rsYdEVBraNv-25I-uQkFrvz5RC8DzQiHEI39vPIJX8yTW8eXzZgnvTqnXrkJVeMhzzVjIiiGIkVCSnXuELk9-QfEejTjbqYJL1-sAVfuVChPL4EhdnSlDy_ZpTq-L84su47TPC-i-_TY4f_LtMPjIsVImhEZKn5R8sl2imtO2bZ4rXvzh2zsk-Bo--SYjDglfg4O5pETzLiL-Ho5D7qpbgzwrqpG8HER3Mz92-QV8wJbQWzPVgGWey2aKJynEhKGZSEQO_3lMaNX4geWkiQKK6WBMMJ1HHNXeCoXXchlKheV1IG1kt3Oma0-Okr4yt-cpELwaWV6YSxOiBCLD250bg",
            "scope": "openid okta.apps.sso",
            "id_token": "ewogICJzdWIiOiAiMDB1MTBjOG51c0xMOWRyWXIxZDciLAogICJ2ZXIiOiAxLAogICJpc3MiOiAiaHR0cHM6Ly9leGFtcGxlLW9pZS5va3RhcHJldmlldy5jb20iLAogICJhdWQiOiAiMG9hNzM2cGhuYWVZT3FVUkoxZDciLAogICJpYXQiOiAxNjgwMTEyMDc0LAogICJleHAiOiAxNjgwMTE1Njc0LAogICJqdGkiOiAiSUQuMUtUUEJIX2hzRmxPQnJvREo2LUlmZFZmQVdiSWUzckkteTVFVXFlYkROcyIsCiAgImFtciI6IFsKICAgICJtZmEiLAogICAgInB3ZCIsCiAgICAiaHdrIiwKICAgICJ1c2VyIgogIF0sCiAgImlkcCI6ICIwMG8xMGM4bnJlNXNlenNpdDFkNyIsCiAgInNpZCI6ICJpZHhtd2d5R0ZvMFJpTzVZeFRYc2p4OEtRIiwKICAiYXV0aF90aW1lIjogMTY4MDExMDg5NSwKICAiYXRfaGFzaCI6ICJtajBpSEVuY1hNSGVEdFgwbnF0OEFnIgp9"
            }

        self.auth_session = {
            'username': self.username,
            'access_token': self.token_response['access_token'],
            'id_token': self.token_response['id_token'],
            'scope': self.token_response['scope']
        }

        self.web_sso_response = {
            "token_type": "N_A",
            "expires_in": 300,
            "access_token": "eyJraWQiOiI0YzRwMkxudmxkdHRSdW56UHN3VzN0d0tPYzVGNkpZN1c3U1l3OEoyaXRRIiwiYWxnIjoiUlMyNTYifQ.ewogICJ2ZXIiOiAxLAogICJqdGkiOiAiV1QuSEhEaU15X1MwM2wwc2VzeVpBaGlLTDFHcGZLYkdGemNDNWtFNk1nb05xQSIsCiAgImlzcyI6ICJodHRwczovL2V4YW1wbGUtb2llLm9rdGFwcmV2aWV3LmNvbSIsCiAgImF1ZCI6ICJodHRwczovL2V4YW1wbGUtb2llLm9rdGFwcmV2aWV3LmNvbS9sb2dpbi90b2tlbi9zc28iLAogICJzdWIiOiAiMDB1MTBjOG51c0xMOWRyWXIxZDciLAogICJpYXQiOiAxNjgwMTEyMDc1LAogICJleHAiOiAxNjgwMTEyMzc1LAogICJvcmciOiAiMDBvMTBjOG5yZTVzZXpzaXQxZDciLAogICJjaWQiOiAiMG9hNzM2cGhuYWVZT3FVUkoxZDciLAogICJzdGkiOiAiWVVoTmFrSnRWV2szVWtWQ2JpOXFNbWMxZEVGS1VVaHJlRkJKZFV0VE9XVnZiblZYWlRaV0wxbDBkV1F2T1dvNGQwaGpUa0U0UkVOdlNESndUR2x4YXciCn0.McCgGTr0C74FNMmSNGiJTOSHbLQ126lyIiPwuQuvK-1gnwHTkWBMcAbUHAqOTl1aUjtQsO1zslFrS63e4BzcxvSedl8NIyerDRCGLmT-ACt4ZWuK7FkZcYKad0InnMeenDSjzCWuE9QErBCHCr4kJV6uWRHS1CcpKOgjH3Adq47pWTecuQK_BbEEG4XhOcek47IjbOowvjbQVq0pVJR68rT0Y-Df60hoL3E5pU6iWpAmlSG3BgueTIWCXx1EWwufWGUFfsPMBsIb4ihyemC-ULfROvU6g72p4dr-F3mz8vzlNLacz-dEe_RXw9AnE7lDOVSVc8F0JSEUV3K5y-sW6g",
            "issued_token_type": "urn:okta:oauth:token-type:web_sso_token"
        }

        self.saml_response = """
        <html><body><form id="appForm" action="https&#x3a;&#x2f;&#x2f;signin.aws.amazon.com&#x2f;saml" method="POST">
    <input name="SAMLResponse" type="hidden" value="PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHNhbWwycDpSZXNwb25zZSBEZXN0aW5hdGlvbj0iaHR0cHM6Ly9zaWduaW4uYXdzLmFtYXpvbi5jb20vc2FtbCIgSUQ9ImlkMTAzODgzMjQ2MjU0OTc3MDkxNzU3MDQ0MTAwIgogICAgSXNzdWVJbnN0YW50PSIyMDIzLTAzLTI5VDE3OjQ3OjU2LjE3NloiIFZlcnNpb249IjIuMCIKICAgIHhtbG5zOnNhbWwycD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOnByb3RvY29sIiB4bWxuczp4cz0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEiPgogICAgPHNhbWwyOklzc3VlciBGb3JtYXQ9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDpuYW1laWQtZm9ybWF0OmVudGl0eSIKICAgICAgICB4bWxuczpzYW1sMj0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFzc2VydGlvbiI+aHR0cDovL3d3dy5va3RhLmNvbS9leGs3MzZuMml4OHNURENZbTFkNzwvc2FtbDI6SXNzdWVyPgogICAgPGRzOlNpZ25hdHVyZSB4bWxuczpkcz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnIyI+CiAgICAgICAgPGRzOlNpZ25lZEluZm8+CiAgICAgICAgICAgIDxkczpDYW5vbmljYWxpemF0aW9uTWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8xMC94bWwtZXhjLWMxNG4jIiAvPgogICAgICAgICAgICA8ZHM6U2lnbmF0dXJlTWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8wNC94bWxkc2lnLW1vcmUjcnNhLXNoYTI1NiIgLz4KICAgICAgICAgICAgPGRzOlJlZmVyZW5jZSBVUkk9IiNpZDEwMzg4MzI0NjI1NDk3NzA5MTc1NzA0NDEwMCI+CiAgICAgICAgICAgICAgICA8ZHM6VHJhbnNmb3Jtcz4KICAgICAgICAgICAgICAgICAgICA8ZHM6VHJhbnNmb3JtIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnI2VudmVsb3BlZC1zaWduYXR1cmUiIC8+CiAgICAgICAgICAgICAgICAgICAgPGRzOlRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyI+CiAgICAgICAgICAgICAgICAgICAgICAgIDxlYzpJbmNsdXNpdmVOYW1lc3BhY2VzIFByZWZpeExpc3Q9InhzIgogICAgICAgICAgICAgICAgICAgICAgICAgICAgeG1sbnM6ZWM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyIgLz4KICAgICAgICAgICAgICAgICAgICA8L2RzOlRyYW5zZm9ybT4KICAgICAgICAgICAgICAgIDwvZHM6VHJhbnNmb3Jtcz4KICAgICAgICAgICAgICAgIDxkczpEaWdlc3RNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGVuYyNzaGEyNTYiIC8+CiAgICAgICAgICAgICAgICA8ZHM6RGlnZXN0VmFsdWU+Q0V6UnRBZVdXaGZvdkhsUGRvb3RmZG9xNDUvcTF3MG1jWUZZNEprekpnMD08L2RzOkRpZ2VzdFZhbHVlPgogICAgICAgICAgICA8L2RzOlJlZmVyZW5jZT4KICAgICAgICA8L2RzOlNpZ25lZEluZm8+CiAgICAgICAgPGRzOlNpZ25hdHVyZVZhbHVlPgogICAgICAgICAgICBDa21YbFJ6clp0YUFFdXFxODFMeXREV1p0YlN3VTlBUTZncFJJWFByWCtlZ05YYmw5eCtNakZFVVE4NU9ZVm5sbk82WFprbGI0TVFsNGdvVDJDZFkvMEIvemtGaUppSGlBdEN1dmlFWkRYeCt4anZURm5jTGUvSkcveTRjYm1xWlVpMlJrV0phSjVzODc2dVVlSGNwcmkrc0ZNWEhMNkc4MENjODBuOTJCaDFLMUNvYXUrekxrQnZYb3pnZ0lZVDNTRFVaVXZQQ21uMFh2cjg0YWtmWHowNzBvM3l3T01qVGFyQWwvT3FFUUV1djh5aHQrcEhqcWVsWGZHaGdnanB6SVVhZ3pkdXEwejBCN2lsRVdPY1JqOW1WckVEZ0dBc1pkRDBLckh0WWVqYjZBb2IrMzhkSnROakNXU2dMWWRBMVhGNlRZUzFNSnorVVkvemxmK1V6OGc9PTwvZHM6U2lnbmF0dXJlVmFsdWU+CiAgICAgICAgPGRzOktleUluZm8+CiAgICAgICAgICAgIDxkczpYNTA5RGF0YT4KICAgICAgICAgICAgICAgIDxkczpYNTA5Q2VydGlmaWNhdGU+TUlJRG9EQ0NBb2lnQXdJQkFnSUdBWVo2MHFySE1BMEdDU3FHU0liM0RRRUJDd1VBTUlHUU1Rc3dDUVlEVlFRR0V3SlZVekVUTUJFRwogICAgICAgICAgICAgICAgICAgIEExVUVDQXdLUTJGc2FXWnZjbTVwWVRFV01CUUdBMVVFQnd3TlUyRnVJRVp5WVc1amFYTmpiekVOTUFzR0ExVUVDZ3dFVDJ0MFlURVUKICAgICAgICAgICAgICAgICAgICBNQklHQTFVRUN3d0xVMU5QVUhKdmRtbGtaWEl4RVRBUEJnTlZCQU1NQ0c1cGEyVXRiMmxsTVJ3d0dnWUpLb1pJaHZjTkFRa0JGZzFwCiAgICAgICAgICAgICAgICAgICAgYm1adlFHOXJkR0V1WTI5dE1CNFhEVEl6TURJeU1qSXdNekF4TWxvWERUTXpNREl5TWpJd016RXhNVm93Z1pBeEN6QUpCZ05WQkFZVAogICAgICAgICAgICAgICAgICAgIEFsVlRNUk13RVFZRFZRUUlEQXBEWVd4cFptOXlibWxoTVJZd0ZBWURWUVFIREExVFlXNGdSbkpoYm1OcGMyTnZNUTB3Q3dZRFZRUUsKICAgICAgICAgICAgICAgICAgICBEQVJQYTNSaE1SUXdFZ1lEVlFRTERBdFRVMDlRY205MmFXUmxjakVSTUE4R0ExVUVBd3dJYm1sclpTMXZhV1V4SERBYUJna3Foa2lHCiAgICAgICAgICAgICAgICAgICAgOXcwQkNRRVdEV2x1Wm05QWIydDBZUzVqYjIwd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUN6dTR5ZQogICAgICAgICAgICAgICAgICAgIElmWmhweEJDck1BWHQvRlE4Y0pUK3VaRjBudmkvMHRSVkJHSS8xZzhEYTBQVEtFbzkyTGFydzFicVhmWnl1L2hwYmVUYWEyR1NuaC8KICAgICAgICAgICAgICAgICAgICA3OVpzQVZlVlpPMVpEZmFLL3VaQ2NIU3lpdGJadXlUdThyVWhqamo2U2drVmdqdllyYWwxM00xM0hVY0NRc1c2Uiswa1J5eU9VM3o3CiAgICAgICAgICAgICAgICAgICAgdTUzbzNiYnpQZEJTMnk4V1IvbEF4ZGJQNnhicnY0c1gzQUhvTUI2UERFNnBSSEQrbFRpbXA5SVhlb1R2ZkIrL3lpSndYODhiYWdJcAogICAgICAgICAgICAgICAgICAgIG41TWRRWVBpT0l4SWRLQnVobFA2RnY0NGhYWlpIVVAwSHNwVW9PZHdaMmRYcnkxMXZRSlFEeUMyTzE4SzdKTXVIaTRjWVdDZVpiRnoKICAgICAgICAgICAgICAgICAgICAxeWJKU1VNRXdOcUtlcUJDOWRJWm1kWSt0N2xib3c1UEFnTUJBQUV3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUdMMU5rcHMzRHhKCiAgICAgICAgICAgICAgICAgICAgWElKMTNtdlN3eTNQQUI2Wnp1NjRGRnZUYXk0d3VhRGlYUHJ6ek53Y05DODhSaURJMXRoeG1EMklFdUYxWlZzT0lqUzl5NkdBNVFpWgogICAgICAgICAgICAgICAgICAgIGZkNUhXOFUrNnhwQVJObDRSSWhiZzB6Z2Vva2ZKUGVzWnFGQnZiWjhLZnMrWTdUTzdhUHFRa3FENzBQaGtSVWZNZk1GaFZaM2hkbGgKICAgICAgICAgICAgICAgICAgICBYSjNIcmNoWkJJdTE3QWo3Zk1kWSs1eE1DWWRjZ2o4MWpzWjU4K3FpeTBLR0hXSUNCUG9DWVlyOERoZmRoSmhqZ1ZBWU5CS0llVXNiCiAgICAgICAgICAgICAgICAgICAgVXYxeUhTUkJ0S1FiN25mcFBlUmVvUGVMa3REUTF5VTNFQmRnc3dDRWg2UytLNzlUYTZUZnFTYXdtaXU1Rm9tUHhrYy9mT05mRFYxYQogICAgICAgICAgICAgICAgICAgIDhnMVBYYnQybTd2WmpkaktveVcwRTErREZpQT08L2RzOlg1MDlDZXJ0aWZpY2F0ZT4KICAgICAgICAgICAgPC9kczpYNTA5RGF0YT4KICAgICAgICA8L2RzOktleUluZm8+CiAgICA8L2RzOlNpZ25hdHVyZT4KICAgIDxzYW1sMnA6U3RhdHVzIHhtbG5zOnNhbWwycD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOnByb3RvY29sIj4KICAgICAgICA8c2FtbDJwOlN0YXR1c0NvZGUgVmFsdWU9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDpzdGF0dXM6U3VjY2VzcyIgLz4KICAgIDwvc2FtbDJwOlN0YXR1cz4KICAgIDxzYW1sMjpBc3NlcnRpb24gSUQ9ImlkMTAzODgzMjQ2MjU2MzkyOTE0Mzg3NDM1NDciIElzc3VlSW5zdGFudD0iMjAyMy0wMy0yOVQxNzo0Nzo1Ni4xNzZaIgogICAgICAgIFZlcnNpb249IjIuMCIgeG1sbnM6c2FtbDI9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphc3NlcnRpb24iCiAgICAgICAgeG1sbnM6eHM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hIj4KICAgICAgICA8c2FtbDI6SXNzdWVyIEZvcm1hdD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOm5hbWVpZC1mb3JtYXQ6ZW50aXR5IgogICAgICAgICAgICB4bWxuczpzYW1sMj0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFzc2VydGlvbiI+CiAgICAgICAgICAgIGh0dHA6Ly93d3cub2t0YS5jb20vZXhrNzM2bjJpeDhzVERDWW0xZDc8L3NhbWwyOklzc3Vlcj4KICAgICAgICA8ZHM6U2lnbmF0dXJlIHhtbG5zOmRzPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjIj4KICAgICAgICAgICAgPGRzOlNpZ25lZEluZm8+CiAgICAgICAgICAgICAgICA8ZHM6Q2Fub25pY2FsaXphdGlvbk1ldGhvZCBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyIgLz4KICAgICAgICAgICAgICAgIDxkczpTaWduYXR1cmVNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNyc2Etc2hhMjU2IiAvPgogICAgICAgICAgICAgICAgPGRzOlJlZmVyZW5jZSBVUkk9IiNpZDEwMzg4MzI0NjI1NjM5MjkxNDM4NzQzNTQ3Ij4KICAgICAgICAgICAgICAgICAgICA8ZHM6VHJhbnNmb3Jtcz4KICAgICAgICAgICAgICAgICAgICAgICAgPGRzOlRyYW5zZm9ybQogICAgICAgICAgICAgICAgICAgICAgICAgICAgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjZW52ZWxvcGVkLXNpZ25hdHVyZSIgLz4KICAgICAgICAgICAgICAgICAgICAgICAgPGRzOlRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8ZWM6SW5jbHVzaXZlTmFtZXNwYWNlcyBQcmVmaXhMaXN0PSJ4cyIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICB4bWxuczplYz0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8xMC94bWwtZXhjLWMxNG4jIiAvPgogICAgICAgICAgICAgICAgICAgICAgICA8L2RzOlRyYW5zZm9ybT4KICAgICAgICAgICAgICAgICAgICA8L2RzOlRyYW5zZm9ybXM+CiAgICAgICAgICAgICAgICAgICAgPGRzOkRpZ2VzdE1ldGhvZCBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMDQveG1sZW5jI3NoYTI1NiIgLz4KICAgICAgICAgICAgICAgICAgICA8ZHM6RGlnZXN0VmFsdWU+d29JZU8reWMvQWF6Q3NweTg2SlhkcWVWRzFselJMdVk5LzdhWXcwYVIvND08L2RzOkRpZ2VzdFZhbHVlPgogICAgICAgICAgICAgICAgPC9kczpSZWZlcmVuY2U+CiAgICAgICAgICAgIDwvZHM6U2lnbmVkSW5mbz4KICAgICAgICAgICAgPGRzOlNpZ25hdHVyZVZhbHVlPgogICAgICAgICAgICAgICAgSUtVMTllR3BUN2hmQXZ6R3M2alYvdFltMFVTK0dPWmdnRXVrWEhIUk1UY2xJM1hzcm83U1Vxdk92NE9RS0szYTJZSHgzZHFzR3hIWUxTTHVIS2dTNXJMRCswYTkvTTFDK2hoRks0MHF2M2ZYVzVzNk9ub2daQjVzTVRtZmJRY2p1RmpSVnFDTlNZZ1g3ZHY5Z2tFUDkyWGpYdDhmNjlwQ2Z0dHdUdElac095R24vWVVLKzJqMnRCVzJuYmp0eDZnQ1BjU2IrZFZPM1ROL01vM0ZwelFKdUhuY0hMZi84TkJPRGlML3MvWjhTZE90MkhSZy96anZuUFRaRXpFcnFvNWZaOGd2T2dwL1dTby80dW0vWHZqOXdBTlorRVF3MUkvdER0YmNwb0NjNXVER2VBbTZpdndEbXQyTTVudWVsVTVOVGp2NnNUQXNnYkZFSmpkdExLdVBBPT08L2RzOlNpZ25hdHVyZVZhbHVlPgogICAgICAgICAgICA8ZHM6S2V5SW5mbz4KICAgICAgICAgICAgICAgIDxkczpYNTA5RGF0YT4KICAgICAgICAgICAgICAgICAgICA8ZHM6WDUwOUNlcnRpZmljYXRlPk1JSURvRENDQW9pZ0F3SUJBZ0lHQVlaNjBxckhNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1JR1FNUXN3Q1FZRFZRUUdFd0pWVXpFVE1CRUcKICAgICAgICAgICAgICAgICAgICAgICAgQTFVRUNBd0tRMkZzYVdadmNtNXBZVEVXTUJRR0ExVUVCd3dOVTJGdUlFWnlZVzVqYVhOamJ6RU5NQXNHQTFVRUNnd0VUMnQwWVRFVQogICAgICAgICAgICAgICAgICAgICAgICBNQklHQTFVRUN3d0xVMU5QVUhKdmRtbGtaWEl4RVRBUEJnTlZCQU1NQ0c1cGEyVXRiMmxsTVJ3d0dnWUpLb1pJaHZjTkFRa0JGZzFwCiAgICAgICAgICAgICAgICAgICAgICAgIGJtWnZRRzlyZEdFdVkyOXRNQjRYRFRJek1ESXlNakl3TXpBeE1sb1hEVE16TURJeU1qSXdNekV4TVZvd2daQXhDekFKQmdOVkJBWVQKICAgICAgICAgICAgICAgICAgICAgICAgQWxWVE1STXdFUVlEVlFRSURBcERZV3hwWm05eWJtbGhNUll3RkFZRFZRUUhEQTFUWVc0Z1JuSmhibU5wYzJOdk1RMHdDd1lEVlFRSwogICAgICAgICAgICAgICAgICAgICAgICBEQVJQYTNSaE1SUXdFZ1lEVlFRTERBdFRVMDlRY205MmFXUmxjakVSTUE4R0ExVUVBd3dJYm1sclpTMXZhV1V4SERBYUJna3Foa2lHCiAgICAgICAgICAgICAgICAgICAgICAgIDl3MEJDUUVXRFdsdVptOUFiMnQwWVM1amIyMHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDenU0eWUKICAgICAgICAgICAgICAgICAgICAgICAgSWZaaHB4QkNyTUFYdC9GUThjSlQrdVpGMG52aS8wdFJWQkdJLzFnOERhMFBUS0VvOTJMYXJ3MWJxWGZaeXUvaHBiZVRhYTJHU25oLwogICAgICAgICAgICAgICAgICAgICAgICA3OVpzQVZlVlpPMVpEZmFLL3VaQ2NIU3lpdGJadXlUdThyVWhqamo2U2drVmdqdllyYWwxM00xM0hVY0NRc1c2Uiswa1J5eU9VM3o3CiAgICAgICAgICAgICAgICAgICAgICAgIHU1M28zYmJ6UGRCUzJ5OFdSL2xBeGRiUDZ4YnJ2NHNYM0FIb01CNlBERTZwUkhEK2xUaW1wOUlYZW9UdmZCKy95aUp3WDg4YmFnSXAKICAgICAgICAgICAgICAgICAgICAgICAgbjVNZFFZUGlPSXhJZEtCdWhsUDZGdjQ0aFhaWkhVUDBIc3BVb09kd1oyZFhyeTExdlFKUUR5QzJPMThLN0pNdUhpNGNZV0NlWmJGegogICAgICAgICAgICAgICAgICAgICAgICAxeWJKU1VNRXdOcUtlcUJDOWRJWm1kWSt0N2xib3c1UEFnTUJBQUV3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUdMMU5rcHMzRHhKCiAgICAgICAgICAgICAgICAgICAgICAgIFhJSjEzbXZTd3kzUEFCNlp6dTY0RkZ2VGF5NHd1YURpWFByenpOd2NOQzg4UmlESTF0aHhtRDJJRXVGMVpWc09JalM5eTZHQTVRaVoKICAgICAgICAgICAgICAgICAgICAgICAgZmQ1SFc4VSs2eHBBUk5sNFJJaGJnMHpnZW9rZkpQZXNacUZCdmJaOEtmcytZN1RPN2FQcVFrcUQ3MFBoa1JVZk1mTUZoVlozaGRsaAogICAgICAgICAgICAgICAgICAgICAgICBYSjNIcmNoWkJJdTE3QWo3Zk1kWSs1eE1DWWRjZ2o4MWpzWjU4K3FpeTBLR0hXSUNCUG9DWVlyOERoZmRoSmhqZ1ZBWU5CS0llVXNiCiAgICAgICAgICAgICAgICAgICAgICAgIFV2MXlIU1JCdEtRYjduZnBQZVJlb1BlTGt0RFExeVUzRUJkZ3N3Q0VoNlMrSzc5VGE2VGZxU2F3bWl1NUZvbVB4a2MvZk9OZkRWMWEKICAgICAgICAgICAgICAgICAgICAgICAgOGcxUFhidDJtN3ZaamRqS295VzBFMStERmlBPTwvZHM6WDUwOUNlcnRpZmljYXRlPgogICAgICAgICAgICAgICAgPC9kczpYNTA5RGF0YT4KICAgICAgICAgICAgPC9kczpLZXlJbmZvPgogICAgICAgIDwvZHM6U2lnbmF0dXJlPgogICAgICAgIDxzYW1sMjpTdWJqZWN0IHhtbG5zOnNhbWwyPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YXNzZXJ0aW9uIj4KICAgICAgICAgICAgPHNhbWwyOk5hbWVJRCBGb3JtYXQ9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDpuYW1laWQtZm9ybWF0OnVuc3BlY2lmaWVkIj4KICAgICAgICAgICAgICAgIGVyaWMucGllcmNlQG5pa2UuY29tPC9zYW1sMjpOYW1lSUQ+CiAgICAgICAgICAgIDxzYW1sMjpTdWJqZWN0Q29uZmlybWF0aW9uIE1ldGhvZD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmNtOmJlYXJlciI+CiAgICAgICAgICAgICAgICA8c2FtbDI6U3ViamVjdENvbmZpcm1hdGlvbkRhdGEgTm90T25PckFmdGVyPSIyMDIzLTAzLTI5VDE3OjUyOjU2LjE3N1oiCiAgICAgICAgICAgICAgICAgICAgUmVjaXBpZW50PSJodHRwczovL3NpZ25pbi5hd3MuYW1hem9uLmNvbS9zYW1sIiAvPgogICAgICAgICAgICA8L3NhbWwyOlN1YmplY3RDb25maXJtYXRpb24+CiAgICAgICAgPC9zYW1sMjpTdWJqZWN0PgogICAgICAgIDxzYW1sMjpDb25kaXRpb25zIE5vdEJlZm9yZT0iMjAyMy0wMy0yOVQxNzo0Mjo1Ni4xNzdaIgogICAgICAgICAgICBOb3RPbk9yQWZ0ZXI9IjIwMjMtMDMtMjlUMTc6NTI6NTYuMTc3WiIKICAgICAgICAgICAgeG1sbnM6c2FtbDI9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphc3NlcnRpb24iPgogICAgICAgICAgICA8c2FtbDI6QXVkaWVuY2VSZXN0cmljdGlvbj4KICAgICAgICAgICAgICAgIDxzYW1sMjpBdWRpZW5jZT51cm46YW1hem9uOndlYnNlcnZpY2VzPC9zYW1sMjpBdWRpZW5jZT4KICAgICAgICAgICAgPC9zYW1sMjpBdWRpZW5jZVJlc3RyaWN0aW9uPgogICAgICAgIDwvc2FtbDI6Q29uZGl0aW9ucz4KICAgICAgICA8c2FtbDI6QXV0aG5TdGF0ZW1lbnQgQXV0aG5JbnN0YW50PSIyMDIzLTAzLTI5VDE3OjI4OjE1LjAwMFoiCiAgICAgICAgICAgIFNlc3Npb25JbmRleD0iaWQxNjgwMTEyMDc2MTc2LjIxMTAzMjU3NTciCiAgICAgICAgICAgIHhtbG5zOnNhbWwyPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YXNzZXJ0aW9uIj4KICAgICAgICAgICAgPHNhbWwyOkF1dGhuQ29udGV4dD4KICAgICAgICAgICAgICAgIDxzYW1sMjpBdXRobkNvbnRleHRDbGFzc1JlZj4KICAgICAgICAgICAgICAgICAgICB1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YWM6Y2xhc3NlczpQYXNzd29yZFByb3RlY3RlZFRyYW5zcG9ydDwvc2FtbDI6QXV0aG5Db250ZXh0Q2xhc3NSZWY+CiAgICAgICAgICAgIDwvc2FtbDI6QXV0aG5Db250ZXh0PgogICAgICAgIDwvc2FtbDI6QXV0aG5TdGF0ZW1lbnQ+CiAgICAgICAgPHNhbWwyOkF0dHJpYnV0ZVN0YXRlbWVudCB4bWxuczpzYW1sMj0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFzc2VydGlvbiI+CiAgICAgICAgICAgIDxzYW1sMjpBdHRyaWJ1dGUgTmFtZT0iaHR0cHM6Ly9hd3MuYW1hem9uLmNvbS9TQU1ML0F0dHJpYnV0ZXMvUm9sZSIKICAgICAgICAgICAgICAgIE5hbWVGb3JtYXQ9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphdHRybmFtZS1mb3JtYXQ6dXJpIj4KICAgICAgICAgICAgICAgIDxzYW1sMjpBdHRyaWJ1dGVWYWx1ZSB4bWxuczp4cz0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEiCiAgICAgICAgICAgICAgICAgICAgeG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeHNpOnR5cGU9InhzOnN0cmluZyI+CiAgICAgICAgICAgICAgICAgICAgYXJuOmF3czppYW06OjEyMzQ1Njc4OTAxMjpzYW1sLXByb3ZpZGVyL09rdGEsYXJuOmF3czppYW06OjEyMzQ1Njc4OTAxMjpyb2xlL1NTTy5BZG1pblJvbGU8L3NhbWwyOkF0dHJpYnV0ZVZhbHVlPgogICAgICAgICAgICAgICAgPHNhbWwyOkF0dHJpYnV0ZVZhbHVlIHhtbG5zOnhzPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSIKICAgICAgICAgICAgICAgICAgICB4bWxuczp4c2k9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hLWluc3RhbmNlIiB4c2k6dHlwZT0ieHM6c3RyaW5nIj4KICAgICAgICAgICAgICAgICAgICBhcm46YXdzOmlhbTo6MTIzNDU2Nzg5MDEyOnNhbWwtcHJvdmlkZXIvT2t0YSxhcm46YXdzOmlhbTo6MTIzNDU2Nzg5MDEyOnJvbGUvU1NPLlJlYWRPbmx5Um9sZTwvc2FtbDI6QXR0cmlidXRlVmFsdWU+CiAgICAgICAgICAgIDwvc2FtbDI6QXR0cmlidXRlPgogICAgICAgICAgICA8c2FtbDI6QXR0cmlidXRlIE5hbWU9Imh0dHBzOi8vYXdzLmFtYXpvbi5jb20vU0FNTC9BdHRyaWJ1dGVzL1JvbGVTZXNzaW9uTmFtZSIKICAgICAgICAgICAgICAgIE5hbWVGb3JtYXQ9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphdHRybmFtZS1mb3JtYXQ6YmFzaWMiPgogICAgICAgICAgICAgICAgPHNhbWwyOkF0dHJpYnV0ZVZhbHVlIHhtbG5zOnhzPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSIKICAgICAgICAgICAgICAgICAgICB4bWxuczp4c2k9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hLWluc3RhbmNlIiB4c2k6dHlwZT0ieHM6c3RyaW5nIj4KICAgICAgICAgICAgICAgICAgICB0ZXN0QGV4YW1wbGUuY29tPC9zYW1sMjpBdHRyaWJ1dGVWYWx1ZT4KICAgICAgICAgICAgPC9zYW1sMjpBdHRyaWJ1dGU+CiAgICAgICAgICAgIDxzYW1sMjpBdHRyaWJ1dGUgTmFtZT0iaHR0cHM6Ly9hd3MuYW1hem9uLmNvbS9TQU1ML0F0dHJpYnV0ZXMvU2Vzc2lvbkR1cmF0aW9uIgogICAgICAgICAgICAgICAgTmFtZUZvcm1hdD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmF0dHJuYW1lLWZvcm1hdDpiYXNpYyI+CiAgICAgICAgICAgICAgICA8c2FtbDI6QXR0cmlidXRlVmFsdWUgeG1sbnM6eHM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hIgogICAgICAgICAgICAgICAgICAgIHhtbG5zOnhzaT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEtaW5zdGFuY2UiIHhzaTp0eXBlPSJ4czpzdHJpbmciPjcyMDA8L3NhbWwyOkF0dHJpYnV0ZVZhbHVlPgogICAgICAgICAgICA8L3NhbWwyOkF0dHJpYnV0ZT4KICAgICAgICA8L3NhbWwyOkF0dHJpYnV0ZVN0YXRlbWVudD4KICAgIDwvc2FtbDI6QXNzZXJ0aW9uPgo8L3NhbWwycDpSZXNwb25zZT4"/>
    <input name="RelayState" type="hidden" value=""/>
</form>
</body>
</html>
        """

        self.saml_data = {
            'SAMLResponse': 'PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHNhbWwycDpSZXNwb25zZSBEZXN0aW5hdGlvbj0iaHR0cHM6Ly9zaWduaW4uYXdzLmFtYXpvbi5jb20vc2FtbCIgSUQ9ImlkMTAzODgzMjQ2MjU0OTc3MDkxNzU3MDQ0MTAwIgogICAgSXNzdWVJbnN0YW50PSIyMDIzLTAzLTI5VDE3OjQ3OjU2LjE3NloiIFZlcnNpb249IjIuMCIKICAgIHhtbG5zOnNhbWwycD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOnByb3RvY29sIiB4bWxuczp4cz0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEiPgogICAgPHNhbWwyOklzc3VlciBGb3JtYXQ9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDpuYW1laWQtZm9ybWF0OmVudGl0eSIKICAgICAgICB4bWxuczpzYW1sMj0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFzc2VydGlvbiI+aHR0cDovL3d3dy5va3RhLmNvbS9leGs3MzZuMml4OHNURENZbTFkNzwvc2FtbDI6SXNzdWVyPgogICAgPGRzOlNpZ25hdHVyZSB4bWxuczpkcz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnIyI+CiAgICAgICAgPGRzOlNpZ25lZEluZm8+CiAgICAgICAgICAgIDxkczpDYW5vbmljYWxpemF0aW9uTWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8xMC94bWwtZXhjLWMxNG4jIiAvPgogICAgICAgICAgICA8ZHM6U2lnbmF0dXJlTWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8wNC94bWxkc2lnLW1vcmUjcnNhLXNoYTI1NiIgLz4KICAgICAgICAgICAgPGRzOlJlZmVyZW5jZSBVUkk9IiNpZDEwMzg4MzI0NjI1NDk3NzA5MTc1NzA0NDEwMCI+CiAgICAgICAgICAgICAgICA8ZHM6VHJhbnNmb3Jtcz4KICAgICAgICAgICAgICAgICAgICA8ZHM6VHJhbnNmb3JtIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnI2VudmVsb3BlZC1zaWduYXR1cmUiIC8+CiAgICAgICAgICAgICAgICAgICAgPGRzOlRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyI+CiAgICAgICAgICAgICAgICAgICAgICAgIDxlYzpJbmNsdXNpdmVOYW1lc3BhY2VzIFByZWZpeExpc3Q9InhzIgogICAgICAgICAgICAgICAgICAgICAgICAgICAgeG1sbnM6ZWM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyIgLz4KICAgICAgICAgICAgICAgICAgICA8L2RzOlRyYW5zZm9ybT4KICAgICAgICAgICAgICAgIDwvZHM6VHJhbnNmb3Jtcz4KICAgICAgICAgICAgICAgIDxkczpEaWdlc3RNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGVuYyNzaGEyNTYiIC8+CiAgICAgICAgICAgICAgICA8ZHM6RGlnZXN0VmFsdWU+Q0V6UnRBZVdXaGZvdkhsUGRvb3RmZG9xNDUvcTF3MG1jWUZZNEprekpnMD08L2RzOkRpZ2VzdFZhbHVlPgogICAgICAgICAgICA8L2RzOlJlZmVyZW5jZT4KICAgICAgICA8L2RzOlNpZ25lZEluZm8+CiAgICAgICAgPGRzOlNpZ25hdHVyZVZhbHVlPgogICAgICAgICAgICBDa21YbFJ6clp0YUFFdXFxODFMeXREV1p0YlN3VTlBUTZncFJJWFByWCtlZ05YYmw5eCtNakZFVVE4NU9ZVm5sbk82WFprbGI0TVFsNGdvVDJDZFkvMEIvemtGaUppSGlBdEN1dmlFWkRYeCt4anZURm5jTGUvSkcveTRjYm1xWlVpMlJrV0phSjVzODc2dVVlSGNwcmkrc0ZNWEhMNkc4MENjODBuOTJCaDFLMUNvYXUrekxrQnZYb3pnZ0lZVDNTRFVaVXZQQ21uMFh2cjg0YWtmWHowNzBvM3l3T01qVGFyQWwvT3FFUUV1djh5aHQrcEhqcWVsWGZHaGdnanB6SVVhZ3pkdXEwejBCN2lsRVdPY1JqOW1WckVEZ0dBc1pkRDBLckh0WWVqYjZBb2IrMzhkSnROakNXU2dMWWRBMVhGNlRZUzFNSnorVVkvemxmK1V6OGc9PTwvZHM6U2lnbmF0dXJlVmFsdWU+CiAgICAgICAgPGRzOktleUluZm8+CiAgICAgICAgICAgIDxkczpYNTA5RGF0YT4KICAgICAgICAgICAgICAgIDxkczpYNTA5Q2VydGlmaWNhdGU+TUlJRG9EQ0NBb2lnQXdJQkFnSUdBWVo2MHFySE1BMEdDU3FHU0liM0RRRUJDd1VBTUlHUU1Rc3dDUVlEVlFRR0V3SlZVekVUTUJFRwogICAgICAgICAgICAgICAgICAgIEExVUVDQXdLUTJGc2FXWnZjbTVwWVRFV01CUUdBMVVFQnd3TlUyRnVJRVp5WVc1amFYTmpiekVOTUFzR0ExVUVDZ3dFVDJ0MFlURVUKICAgICAgICAgICAgICAgICAgICBNQklHQTFVRUN3d0xVMU5QVUhKdmRtbGtaWEl4RVRBUEJnTlZCQU1NQ0c1cGEyVXRiMmxsTVJ3d0dnWUpLb1pJaHZjTkFRa0JGZzFwCiAgICAgICAgICAgICAgICAgICAgYm1adlFHOXJkR0V1WTI5dE1CNFhEVEl6TURJeU1qSXdNekF4TWxvWERUTXpNREl5TWpJd016RXhNVm93Z1pBeEN6QUpCZ05WQkFZVAogICAgICAgICAgICAgICAgICAgIEFsVlRNUk13RVFZRFZRUUlEQXBEWVd4cFptOXlibWxoTVJZd0ZBWURWUVFIREExVFlXNGdSbkpoYm1OcGMyTnZNUTB3Q3dZRFZRUUsKICAgICAgICAgICAgICAgICAgICBEQVJQYTNSaE1SUXdFZ1lEVlFRTERBdFRVMDlRY205MmFXUmxjakVSTUE4R0ExVUVBd3dJYm1sclpTMXZhV1V4SERBYUJna3Foa2lHCiAgICAgICAgICAgICAgICAgICAgOXcwQkNRRVdEV2x1Wm05QWIydDBZUzVqYjIwd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUN6dTR5ZQogICAgICAgICAgICAgICAgICAgIElmWmhweEJDck1BWHQvRlE4Y0pUK3VaRjBudmkvMHRSVkJHSS8xZzhEYTBQVEtFbzkyTGFydzFicVhmWnl1L2hwYmVUYWEyR1NuaC8KICAgICAgICAgICAgICAgICAgICA3OVpzQVZlVlpPMVpEZmFLL3VaQ2NIU3lpdGJadXlUdThyVWhqamo2U2drVmdqdllyYWwxM00xM0hVY0NRc1c2Uiswa1J5eU9VM3o3CiAgICAgICAgICAgICAgICAgICAgdTUzbzNiYnpQZEJTMnk4V1IvbEF4ZGJQNnhicnY0c1gzQUhvTUI2UERFNnBSSEQrbFRpbXA5SVhlb1R2ZkIrL3lpSndYODhiYWdJcAogICAgICAgICAgICAgICAgICAgIG41TWRRWVBpT0l4SWRLQnVobFA2RnY0NGhYWlpIVVAwSHNwVW9PZHdaMmRYcnkxMXZRSlFEeUMyTzE4SzdKTXVIaTRjWVdDZVpiRnoKICAgICAgICAgICAgICAgICAgICAxeWJKU1VNRXdOcUtlcUJDOWRJWm1kWSt0N2xib3c1UEFnTUJBQUV3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUdMMU5rcHMzRHhKCiAgICAgICAgICAgICAgICAgICAgWElKMTNtdlN3eTNQQUI2Wnp1NjRGRnZUYXk0d3VhRGlYUHJ6ek53Y05DODhSaURJMXRoeG1EMklFdUYxWlZzT0lqUzl5NkdBNVFpWgogICAgICAgICAgICAgICAgICAgIGZkNUhXOFUrNnhwQVJObDRSSWhiZzB6Z2Vva2ZKUGVzWnFGQnZiWjhLZnMrWTdUTzdhUHFRa3FENzBQaGtSVWZNZk1GaFZaM2hkbGgKICAgICAgICAgICAgICAgICAgICBYSjNIcmNoWkJJdTE3QWo3Zk1kWSs1eE1DWWRjZ2o4MWpzWjU4K3FpeTBLR0hXSUNCUG9DWVlyOERoZmRoSmhqZ1ZBWU5CS0llVXNiCiAgICAgICAgICAgICAgICAgICAgVXYxeUhTUkJ0S1FiN25mcFBlUmVvUGVMa3REUTF5VTNFQmRnc3dDRWg2UytLNzlUYTZUZnFTYXdtaXU1Rm9tUHhrYy9mT05mRFYxYQogICAgICAgICAgICAgICAgICAgIDhnMVBYYnQybTd2WmpkaktveVcwRTErREZpQT08L2RzOlg1MDlDZXJ0aWZpY2F0ZT4KICAgICAgICAgICAgPC9kczpYNTA5RGF0YT4KICAgICAgICA8L2RzOktleUluZm8+CiAgICA8L2RzOlNpZ25hdHVyZT4KICAgIDxzYW1sMnA6U3RhdHVzIHhtbG5zOnNhbWwycD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOnByb3RvY29sIj4KICAgICAgICA8c2FtbDJwOlN0YXR1c0NvZGUgVmFsdWU9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDpzdGF0dXM6U3VjY2VzcyIgLz4KICAgIDwvc2FtbDJwOlN0YXR1cz4KICAgIDxzYW1sMjpBc3NlcnRpb24gSUQ9ImlkMTAzODgzMjQ2MjU2MzkyOTE0Mzg3NDM1NDciIElzc3VlSW5zdGFudD0iMjAyMy0wMy0yOVQxNzo0Nzo1Ni4xNzZaIgogICAgICAgIFZlcnNpb249IjIuMCIgeG1sbnM6c2FtbDI9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphc3NlcnRpb24iCiAgICAgICAgeG1sbnM6eHM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hIj4KICAgICAgICA8c2FtbDI6SXNzdWVyIEZvcm1hdD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOm5hbWVpZC1mb3JtYXQ6ZW50aXR5IgogICAgICAgICAgICB4bWxuczpzYW1sMj0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFzc2VydGlvbiI+CiAgICAgICAgICAgIGh0dHA6Ly93d3cub2t0YS5jb20vZXhrNzM2bjJpeDhzVERDWW0xZDc8L3NhbWwyOklzc3Vlcj4KICAgICAgICA8ZHM6U2lnbmF0dXJlIHhtbG5zOmRzPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjIj4KICAgICAgICAgICAgPGRzOlNpZ25lZEluZm8+CiAgICAgICAgICAgICAgICA8ZHM6Q2Fub25pY2FsaXphdGlvbk1ldGhvZCBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyIgLz4KICAgICAgICAgICAgICAgIDxkczpTaWduYXR1cmVNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNyc2Etc2hhMjU2IiAvPgogICAgICAgICAgICAgICAgPGRzOlJlZmVyZW5jZSBVUkk9IiNpZDEwMzg4MzI0NjI1NjM5MjkxNDM4NzQzNTQ3Ij4KICAgICAgICAgICAgICAgICAgICA8ZHM6VHJhbnNmb3Jtcz4KICAgICAgICAgICAgICAgICAgICAgICAgPGRzOlRyYW5zZm9ybQogICAgICAgICAgICAgICAgICAgICAgICAgICAgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjZW52ZWxvcGVkLXNpZ25hdHVyZSIgLz4KICAgICAgICAgICAgICAgICAgICAgICAgPGRzOlRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8ZWM6SW5jbHVzaXZlTmFtZXNwYWNlcyBQcmVmaXhMaXN0PSJ4cyIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICB4bWxuczplYz0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8xMC94bWwtZXhjLWMxNG4jIiAvPgogICAgICAgICAgICAgICAgICAgICAgICA8L2RzOlRyYW5zZm9ybT4KICAgICAgICAgICAgICAgICAgICA8L2RzOlRyYW5zZm9ybXM+CiAgICAgICAgICAgICAgICAgICAgPGRzOkRpZ2VzdE1ldGhvZCBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMDQveG1sZW5jI3NoYTI1NiIgLz4KICAgICAgICAgICAgICAgICAgICA8ZHM6RGlnZXN0VmFsdWU+d29JZU8reWMvQWF6Q3NweTg2SlhkcWVWRzFselJMdVk5LzdhWXcwYVIvND08L2RzOkRpZ2VzdFZhbHVlPgogICAgICAgICAgICAgICAgPC9kczpSZWZlcmVuY2U+CiAgICAgICAgICAgIDwvZHM6U2lnbmVkSW5mbz4KICAgICAgICAgICAgPGRzOlNpZ25hdHVyZVZhbHVlPgogICAgICAgICAgICAgICAgSUtVMTllR3BUN2hmQXZ6R3M2alYvdFltMFVTK0dPWmdnRXVrWEhIUk1UY2xJM1hzcm83U1Vxdk92NE9RS0szYTJZSHgzZHFzR3hIWUxTTHVIS2dTNXJMRCswYTkvTTFDK2hoRks0MHF2M2ZYVzVzNk9ub2daQjVzTVRtZmJRY2p1RmpSVnFDTlNZZ1g3ZHY5Z2tFUDkyWGpYdDhmNjlwQ2Z0dHdUdElac095R24vWVVLKzJqMnRCVzJuYmp0eDZnQ1BjU2IrZFZPM1ROL01vM0ZwelFKdUhuY0hMZi84TkJPRGlML3MvWjhTZE90MkhSZy96anZuUFRaRXpFcnFvNWZaOGd2T2dwL1dTby80dW0vWHZqOXdBTlorRVF3MUkvdER0YmNwb0NjNXVER2VBbTZpdndEbXQyTTVudWVsVTVOVGp2NnNUQXNnYkZFSmpkdExLdVBBPT08L2RzOlNpZ25hdHVyZVZhbHVlPgogICAgICAgICAgICA8ZHM6S2V5SW5mbz4KICAgICAgICAgICAgICAgIDxkczpYNTA5RGF0YT4KICAgICAgICAgICAgICAgICAgICA8ZHM6WDUwOUNlcnRpZmljYXRlPk1JSURvRENDQW9pZ0F3SUJBZ0lHQVlaNjBxckhNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1JR1FNUXN3Q1FZRFZRUUdFd0pWVXpFVE1CRUcKICAgICAgICAgICAgICAgICAgICAgICAgQTFVRUNBd0tRMkZzYVdadmNtNXBZVEVXTUJRR0ExVUVCd3dOVTJGdUlFWnlZVzVqYVhOamJ6RU5NQXNHQTFVRUNnd0VUMnQwWVRFVQogICAgICAgICAgICAgICAgICAgICAgICBNQklHQTFVRUN3d0xVMU5QVUhKdmRtbGtaWEl4RVRBUEJnTlZCQU1NQ0c1cGEyVXRiMmxsTVJ3d0dnWUpLb1pJaHZjTkFRa0JGZzFwCiAgICAgICAgICAgICAgICAgICAgICAgIGJtWnZRRzlyZEdFdVkyOXRNQjRYRFRJek1ESXlNakl3TXpBeE1sb1hEVE16TURJeU1qSXdNekV4TVZvd2daQXhDekFKQmdOVkJBWVQKICAgICAgICAgICAgICAgICAgICAgICAgQWxWVE1STXdFUVlEVlFRSURBcERZV3hwWm05eWJtbGhNUll3RkFZRFZRUUhEQTFUWVc0Z1JuSmhibU5wYzJOdk1RMHdDd1lEVlFRSwogICAgICAgICAgICAgICAgICAgICAgICBEQVJQYTNSaE1SUXdFZ1lEVlFRTERBdFRVMDlRY205MmFXUmxjakVSTUE4R0ExVUVBd3dJYm1sclpTMXZhV1V4SERBYUJna3Foa2lHCiAgICAgICAgICAgICAgICAgICAgICAgIDl3MEJDUUVXRFdsdVptOUFiMnQwWVM1amIyMHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDenU0eWUKICAgICAgICAgICAgICAgICAgICAgICAgSWZaaHB4QkNyTUFYdC9GUThjSlQrdVpGMG52aS8wdFJWQkdJLzFnOERhMFBUS0VvOTJMYXJ3MWJxWGZaeXUvaHBiZVRhYTJHU25oLwogICAgICAgICAgICAgICAgICAgICAgICA3OVpzQVZlVlpPMVpEZmFLL3VaQ2NIU3lpdGJadXlUdThyVWhqamo2U2drVmdqdllyYWwxM00xM0hVY0NRc1c2Uiswa1J5eU9VM3o3CiAgICAgICAgICAgICAgICAgICAgICAgIHU1M28zYmJ6UGRCUzJ5OFdSL2xBeGRiUDZ4YnJ2NHNYM0FIb01CNlBERTZwUkhEK2xUaW1wOUlYZW9UdmZCKy95aUp3WDg4YmFnSXAKICAgICAgICAgICAgICAgICAgICAgICAgbjVNZFFZUGlPSXhJZEtCdWhsUDZGdjQ0aFhaWkhVUDBIc3BVb09kd1oyZFhyeTExdlFKUUR5QzJPMThLN0pNdUhpNGNZV0NlWmJGegogICAgICAgICAgICAgICAgICAgICAgICAxeWJKU1VNRXdOcUtlcUJDOWRJWm1kWSt0N2xib3c1UEFnTUJBQUV3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUdMMU5rcHMzRHhKCiAgICAgICAgICAgICAgICAgICAgICAgIFhJSjEzbXZTd3kzUEFCNlp6dTY0RkZ2VGF5NHd1YURpWFByenpOd2NOQzg4UmlESTF0aHhtRDJJRXVGMVpWc09JalM5eTZHQTVRaVoKICAgICAgICAgICAgICAgICAgICAgICAgZmQ1SFc4VSs2eHBBUk5sNFJJaGJnMHpnZW9rZkpQZXNacUZCdmJaOEtmcytZN1RPN2FQcVFrcUQ3MFBoa1JVZk1mTUZoVlozaGRsaAogICAgICAgICAgICAgICAgICAgICAgICBYSjNIcmNoWkJJdTE3QWo3Zk1kWSs1eE1DWWRjZ2o4MWpzWjU4K3FpeTBLR0hXSUNCUG9DWVlyOERoZmRoSmhqZ1ZBWU5CS0llVXNiCiAgICAgICAgICAgICAgICAgICAgICAgIFV2MXlIU1JCdEtRYjduZnBQZVJlb1BlTGt0RFExeVUzRUJkZ3N3Q0VoNlMrSzc5VGE2VGZxU2F3bWl1NUZvbVB4a2MvZk9OZkRWMWEKICAgICAgICAgICAgICAgICAgICAgICAgOGcxUFhidDJtN3ZaamRqS295VzBFMStERmlBPTwvZHM6WDUwOUNlcnRpZmljYXRlPgogICAgICAgICAgICAgICAgPC9kczpYNTA5RGF0YT4KICAgICAgICAgICAgPC9kczpLZXlJbmZvPgogICAgICAgIDwvZHM6U2lnbmF0dXJlPgogICAgICAgIDxzYW1sMjpTdWJqZWN0IHhtbG5zOnNhbWwyPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YXNzZXJ0aW9uIj4KICAgICAgICAgICAgPHNhbWwyOk5hbWVJRCBGb3JtYXQ9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDpuYW1laWQtZm9ybWF0OnVuc3BlY2lmaWVkIj4KICAgICAgICAgICAgICAgIGVyaWMucGllcmNlQG5pa2UuY29tPC9zYW1sMjpOYW1lSUQ+CiAgICAgICAgICAgIDxzYW1sMjpTdWJqZWN0Q29uZmlybWF0aW9uIE1ldGhvZD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmNtOmJlYXJlciI+CiAgICAgICAgICAgICAgICA8c2FtbDI6U3ViamVjdENvbmZpcm1hdGlvbkRhdGEgTm90T25PckFmdGVyPSIyMDIzLTAzLTI5VDE3OjUyOjU2LjE3N1oiCiAgICAgICAgICAgICAgICAgICAgUmVjaXBpZW50PSJodHRwczovL3NpZ25pbi5hd3MuYW1hem9uLmNvbS9zYW1sIiAvPgogICAgICAgICAgICA8L3NhbWwyOlN1YmplY3RDb25maXJtYXRpb24+CiAgICAgICAgPC9zYW1sMjpTdWJqZWN0PgogICAgICAgIDxzYW1sMjpDb25kaXRpb25zIE5vdEJlZm9yZT0iMjAyMy0wMy0yOVQxNzo0Mjo1Ni4xNzdaIgogICAgICAgICAgICBOb3RPbk9yQWZ0ZXI9IjIwMjMtMDMtMjlUMTc6NTI6NTYuMTc3WiIKICAgICAgICAgICAgeG1sbnM6c2FtbDI9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphc3NlcnRpb24iPgogICAgICAgICAgICA8c2FtbDI6QXVkaWVuY2VSZXN0cmljdGlvbj4KICAgICAgICAgICAgICAgIDxzYW1sMjpBdWRpZW5jZT51cm46YW1hem9uOndlYnNlcnZpY2VzPC9zYW1sMjpBdWRpZW5jZT4KICAgICAgICAgICAgPC9zYW1sMjpBdWRpZW5jZVJlc3RyaWN0aW9uPgogICAgICAgIDwvc2FtbDI6Q29uZGl0aW9ucz4KICAgICAgICA8c2FtbDI6QXV0aG5TdGF0ZW1lbnQgQXV0aG5JbnN0YW50PSIyMDIzLTAzLTI5VDE3OjI4OjE1LjAwMFoiCiAgICAgICAgICAgIFNlc3Npb25JbmRleD0iaWQxNjgwMTEyMDc2MTc2LjIxMTAzMjU3NTciCiAgICAgICAgICAgIHhtbG5zOnNhbWwyPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YXNzZXJ0aW9uIj4KICAgICAgICAgICAgPHNhbWwyOkF1dGhuQ29udGV4dD4KICAgICAgICAgICAgICAgIDxzYW1sMjpBdXRobkNvbnRleHRDbGFzc1JlZj4KICAgICAgICAgICAgICAgICAgICB1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YWM6Y2xhc3NlczpQYXNzd29yZFByb3RlY3RlZFRyYW5zcG9ydDwvc2FtbDI6QXV0aG5Db250ZXh0Q2xhc3NSZWY+CiAgICAgICAgICAgIDwvc2FtbDI6QXV0aG5Db250ZXh0PgogICAgICAgIDwvc2FtbDI6QXV0aG5TdGF0ZW1lbnQ+CiAgICAgICAgPHNhbWwyOkF0dHJpYnV0ZVN0YXRlbWVudCB4bWxuczpzYW1sMj0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFzc2VydGlvbiI+CiAgICAgICAgICAgIDxzYW1sMjpBdHRyaWJ1dGUgTmFtZT0iaHR0cHM6Ly9hd3MuYW1hem9uLmNvbS9TQU1ML0F0dHJpYnV0ZXMvUm9sZSIKICAgICAgICAgICAgICAgIE5hbWVGb3JtYXQ9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphdHRybmFtZS1mb3JtYXQ6dXJpIj4KICAgICAgICAgICAgICAgIDxzYW1sMjpBdHRyaWJ1dGVWYWx1ZSB4bWxuczp4cz0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEiCiAgICAgICAgICAgICAgICAgICAgeG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeHNpOnR5cGU9InhzOnN0cmluZyI+CiAgICAgICAgICAgICAgICAgICAgYXJuOmF3czppYW06OjEyMzQ1Njc4OTAxMjpzYW1sLXByb3ZpZGVyL09rdGEsYXJuOmF3czppYW06OjEyMzQ1Njc4OTAxMjpyb2xlL1NTTy5BZG1pblJvbGU8L3NhbWwyOkF0dHJpYnV0ZVZhbHVlPgogICAgICAgICAgICAgICAgPHNhbWwyOkF0dHJpYnV0ZVZhbHVlIHhtbG5zOnhzPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSIKICAgICAgICAgICAgICAgICAgICB4bWxuczp4c2k9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hLWluc3RhbmNlIiB4c2k6dHlwZT0ieHM6c3RyaW5nIj4KICAgICAgICAgICAgICAgICAgICBhcm46YXdzOmlhbTo6MTIzNDU2Nzg5MDEyOnNhbWwtcHJvdmlkZXIvT2t0YSxhcm46YXdzOmlhbTo6MTIzNDU2Nzg5MDEyOnJvbGUvU1NPLlJlYWRPbmx5Um9sZTwvc2FtbDI6QXR0cmlidXRlVmFsdWU+CiAgICAgICAgICAgIDwvc2FtbDI6QXR0cmlidXRlPgogICAgICAgICAgICA8c2FtbDI6QXR0cmlidXRlIE5hbWU9Imh0dHBzOi8vYXdzLmFtYXpvbi5jb20vU0FNTC9BdHRyaWJ1dGVzL1JvbGVTZXNzaW9uTmFtZSIKICAgICAgICAgICAgICAgIE5hbWVGb3JtYXQ9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphdHRybmFtZS1mb3JtYXQ6YmFzaWMiPgogICAgICAgICAgICAgICAgPHNhbWwyOkF0dHJpYnV0ZVZhbHVlIHhtbG5zOnhzPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSIKICAgICAgICAgICAgICAgICAgICB4bWxuczp4c2k9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hLWluc3RhbmNlIiB4c2k6dHlwZT0ieHM6c3RyaW5nIj4KICAgICAgICAgICAgICAgICAgICB0ZXN0QGV4YW1wbGUuY29tPC9zYW1sMjpBdHRyaWJ1dGVWYWx1ZT4KICAgICAgICAgICAgPC9zYW1sMjpBdHRyaWJ1dGU+CiAgICAgICAgICAgIDxzYW1sMjpBdHRyaWJ1dGUgTmFtZT0iaHR0cHM6Ly9hd3MuYW1hem9uLmNvbS9TQU1ML0F0dHJpYnV0ZXMvU2Vzc2lvbkR1cmF0aW9uIgogICAgICAgICAgICAgICAgTmFtZUZvcm1hdD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmF0dHJuYW1lLWZvcm1hdDpiYXNpYyI+CiAgICAgICAgICAgICAgICA8c2FtbDI6QXR0cmlidXRlVmFsdWUgeG1sbnM6eHM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hIgogICAgICAgICAgICAgICAgICAgIHhtbG5zOnhzaT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEtaW5zdGFuY2UiIHhzaTp0eXBlPSJ4czpzdHJpbmciPjcyMDA8L3NhbWwyOkF0dHJpYnV0ZVZhbHVlPgogICAgICAgICAgICA8L3NhbWwyOkF0dHJpYnV0ZT4KICAgICAgICA8L3NhbWwyOkF0dHJpYnV0ZVN0YXRlbWVudD4KICAgIDwvc2FtbDI6QXNzZXJ0aW9uPgo8L3NhbWwycDpSZXNwb25zZT4',
            'RelayState': '',
            'TargetUrl': 'https://signin.aws.amazon.com/saml'
        }
        
    def setUp_client(self, okta_org_url, client_id, verify_ssl_certs):
        client = OktaIdentityEngine(ui.default, okta_org_url, client_id, verify_ssl_certs)
        client.req_session = requests
        return client

    def test_get_headers(self):
        """Testing that get_headers returns the expected results"""
        header = self.client._get_headers()
        self.assertEqual(header['Accept'], 'application/json')

    @responses.activate
    def test_start_device_flow(self):
        """Test that initial authentication works with OIE"""

        responses.add(responses.POST, self.okta_org_url + '/oauth2/v1/device/authorize', status=200, body=json.dumps(self.device_response))
        result = self.client._start_device_flow()
        self.assertEqual(result, {'apiResponse': self.device_response})
    
    @responses.activate
    def test_get_user_tokens(self):
        """Test retrieving Access/ID Token from OIE"""

        responses.add(responses.POST, self.okta_org_url + '/oauth2/v1/token', status=200, body=json.dumps(self.token_response))
        result = self.client._get_user_tokens(self.device_code)
        self.assertEqual(result, self.token_response)
    
    @responses.activate
    def test_auth_session(self):
        """Test login to OIE"""

        responses.add(responses.POST, self.okta_org_url + '/oauth2/v1/device/authorize', status=200, body=json.dumps(self.device_response))
        responses.add(responses.POST, self.okta_org_url + '/oauth2/v1/token', status=200, body=json.dumps(self.token_response))
        result = self.client.auth_session()
        self.assertEqual(result, self.auth_session)
    
    @responses.activate
    def test_saml_response(self):
        """Test SAML response in OIE""" 

        responses.add(responses.POST, self.okta_org_url + '/oauth2/v1/token', status=200, body=json.dumps(self.web_sso_response))
        responses.add(responses.GET, self.okta_org_url + '/login/token/sso', status=200, body=self.saml_response)
        
        result = self.client.get_saml_response(self.server_embed_link, self.auth_session)
        self.assertEqual(result, self.saml_data)

#     @responses.activate
#     def test_login_send_sms(self):
#         """Test that SMS messages can be requested for MFA"""

#         verify_response = {
#             "stateToken": "00Wf8xZJ79mSoTYnJqXbvRegT8QB1EX1IBVk1TU7KI",
#             "type": "SESSION_STEP_UP",
#             "expiresAt": "2017-06-15T15:06:10.000Z",
#             "status": "MFA_CHALLENGE",
#             "_embedded": {
#                 "user": {
#                     "id": "00u8cakq7vQwtK7sR0h7",
#                     "profile": {
#                         "login": "Jane.Doe@example.com",
#                         "firstName": "Jane",
#                         "lastName": "Doe",
#                         "locale": "en",
#                         "timeZone": "America/Los_Angeles"
#                     }
#                 },
#                 "factor": {
#                     "id": "sms9hmdk2qvhjOQQ30h7",
#                     "factorType": "sms",
#                     "provider": "OKTA",
#                     "vendorName": "OKTA",
#                     "profile": {
#                         "phoneNumber": "+1 XXX-XXX-1234"
#                     }
#                 },
#                 "policy": {
#                     "allowRememberDevice": False,
#                     "rememberDeviceLifetimeInMinutes": 0,
#                     "rememberDeviceByDefault": False
#                 },
#                 "target": {
#                     "type": "APP",
#                     "name": "gimmecredsserver",
#                     "label": "Gimme-Creds-Server (Dev)",
#                     "_links": {
#                         "logo": {
#                             "name": "medium",
#                             "href": "https://op1static.oktacdn.com/bc/globalFileStoreRecord?id=gfsatgifysE8NG37F0h7",
#                             "type": "image/png"
#                         }
#                     }
#                 }
#             },
#             "_links": {
#                 "next": {
#                     "name": "verify",
#                     "href": "https://example.okta.com/api/v1/authn/factors/sms9hmdk2qvhjOQQ30h7/verify",
#                     "hints": {
#                         "allow": [
#                             "POST"
#                         ]
#                     }
#                 },
#                 "cancel": {
#                     "href": "https://example.okta.com/api/v1/authn/cancel",
#                     "hints": {
#                         "allow": [
#                             "POST"
#                         ]
#                     }
#                 },
#                 "prev": {
#                     "href": "https://example.okta.com/api/v1/authn/previous",
#                     "hints": {
#                         "allow": [
#                             "POST"
#                         ]
#                     }
#                 },
#                 "resend": [
#                     {
#                         "name": "sms",
#                         "href": "https://example.okta.com/api/v1/authn/factors/sms9hmdk2qvhjOQQ30h7/verify/resend",
#                         "hints": {
#                             "allow": [
#                                 "POST"
#                             ]
#                         }
#                     }
#                 ]
#             }
#         }

#         responses.add(responses.POST, 'https://example.okta.com/api/v1/authn/factors/sms9hmdk2qvhjOQQ30h7/verify', status=200, body=json.dumps(verify_response))
#         result = self.client._login_send_sms(self.state_token, self.sms_factor)
#         self.assertEqual(result, {'stateToken': self.state_token, 'apiResponse': verify_response})

#     @responses.activate
#     def test_login_send_push(self):
#         """Test that Okta Verify can be used for MFA"""

#         verify_response = {
#     "stateToken": "00Wf8xZJ79mSoTYnJqXbvRegT8QB1EX1IBVk1TU7KI",
#     "type": "SESSION_STEP_UP",
#     "expiresAt": "2017-06-15T22:32:40.000Z",
#     "status": "MFA_CHALLENGE",
#     "factorResult": "WAITING",
#     "_embedded": {
#         "user": {
#             "id": "00u8p8560rXMQ95cP0h7",
#             "profile": {
#                 "login": "jane.doe@example.com",
#                 "firstName": "Jane",
#                 "lastName": "Doe",
#                 "locale": "en",
#                 "timeZone": "America/Los_Angeles"
#             }
#         },
#         "factor": {
#             "id": "opf9ei43pbAgb2qgc0h7",
#             "factorType": "push",
#             "provider": "OKTA",
#             "vendorName": "OKTA",
#             "profile": {
#                 "credentialId": "jane.doe@example.com",
#                 "deviceType": "SmartPhone_IPhone",
#                 "keys": [
#                     {
#                         "kty": "PKIX",
#                         "use": "sig",
#                         "kid": "default",
#                         "x5c": [
#                             "fdsfsdfsdfsd"
#                         ]
#                     }
#                 ],
#                 "name": "Jane.Doe iPhone",
#                 "platform": "IOS",
#                 "version": "10.2.1"
#             }
#         },
#         "policy": {
#             "allowRememberDevice": False,
#             "rememberDeviceLifetimeInMinutes": 0,
#             "rememberDeviceByDefault": False
#         },
#         "target": {
#             "type": "APP",
#             "name": "gimmecredstest",
#             "label": "Gimme-Creds-Test",
#             "_links": {
#                 "logo": {
#                     "name": "medium",
#                     "href": "https://op1static.oktacdn.com/bc/globalFileStoreRecord?id=gfsatgifysE8NG37F0h7",
#                     "type": "image/png"
#                 }
#             }
#         }
#     },
#     "_links": {
#         "next": {
#             "name": "poll",
#             "href": "https://example.okta.com/api/v1/authn/factors/opf9ei43pbAgb2qgc0h7/verify",
#             "hints": {
#                 "allow": [
#                     "POST"
#                 ]
#             }
#         },
#         "cancel": {
#             "href": "https://example.okta.com/api/v1/authn/cancel",
#             "hints": {
#                 "allow": [
#                     "POST"
#                 ]
#             }
#         },
#         "prev": {
#             "href": "https://example.okta.com/api/v1/authn/previous",
#             "hints": {
#                 "allow": [
#                     "POST"
#                 ]
#             }
#         },
#         "resend": [
#             {
#                 "name": "push",
#                 "href": "https://example.okta.com/api/v1/authn/factors/opf9ei43pbAgb2qgc0h7/verify/resend",
#                 "hints": {
#                     "allow": [
#                         "POST"
#                     ]
#                 }
#             }
#         ]
#     }
# }

#         responses.add(responses.POST, 'https://example.okta.com/api/v1/authn/factors/opf9ei43pbAgb2qgc0h7/verify', status=200, body=json.dumps(verify_response))
#         result = self.client._login_send_push(self.state_token, self.push_factor)
#         self.assertEqual(result, {'stateToken': self.state_token, 'apiResponse': verify_response})

#     @responses.activate
#     @patch('getpass.getpass', return_value='1234qwert')
#     def test_login_input_mfa_challenge(self, mock_pass):
#         """Test that MFA works with Okta"""

#         verify_response = {
#             "stateToken": "00Wf8xZJ79mSoTYnJqXbvRegT8QB1EX1IBVk1TU7KI",
#             "type": "SESSION_STEP_UP",
#             "expiresAt": "2017-06-15T15:07:27.000Z",
#             "status": "SUCCESS",
#             "_embedded": {
#                 "user": {
#                     "id": "00u8p8560rXMQ95cP0h7",
#                     "profile": {
#                         "login": "jane.doe@example.com",
#                         "firstName": "Jane",
#                         "lastName": "Doe",
#                         "locale": "en",
#                         "timeZone": "America/Los_Angeles"
#                     }
#                 },
#                 "target": {
#                     "type": "APP",
#                     "name": "gimmecredsserver",
#                     "label": "Gimme-Creds-Server (Dev)",
#                     "_links": {
#                         "logo": {
#                             "name": "medium",
#                             "href": "https://op1static.oktacdn.com/bc/globalFileStoreRecord?id=gfsatgifysE8NG37F0h7",
#                             "type": "image/png"
#                         }
#                     }
#                 }
#             },
#             "_links": {
#                 "next": {
#                     "name": "original",
#                     "href": "https://example.okta.com/login/step-up/redirect?stateToken=00Wf8xZJ79mSoTYnJqXbvRegT8QB1EX1IBVk1TU7KI",
#                     "hints": {
#                         "allow": [
#                             "GET"
#                         ]
#                     }
#                 }
#             }
#         }
#         responses.add(responses.POST, 'https://example.okta.com/api/v1/authn/factors/sms9hmdk2qvhjOQQ30h7/verify', status=200, body=json.dumps(verify_response))
#         result = self.client._login_input_mfa_challenge(self.state_token, 'https://example.okta.com/api/v1/authn/factors/sms9hmdk2qvhjOQQ30h7/verify')
#         self.assertEqual(result, {'stateToken': self.state_token, 'apiResponse': verify_response})


#     @responses.activate
#     def test_check_push_result(self):
#         """Test that the Okta Verify response was successful"""

#         verify_response = {
#     "stateToken": "00Wf8xZJ79mSoTYnJqXbvRegT8QB1EX1IBVk1TU7KI",
#     "type": "SESSION_STEP_UP",
#     "expiresAt": "2017-06-15T22:32:40.000Z",
#     "status": "MFA_CHALLENGE",
#     "factorResult": "WAITING",
#     "_embedded": {
#         "user": {
#             "id": "00u8p8560rXMQ95cP0h7",
#             "profile": {
#                 "login": "jane.doe@example.com",
#                 "firstName": "Jane",
#                 "lastName": "Doe",
#                 "locale": "en",
#                 "timeZone": "America/Los_Angeles"
#             }
#         },
#         "factor": {
#             "id": "opf9ei43pbAgb2qgc0h7",
#             "factorType": "push",
#             "provider": "OKTA",
#             "vendorName": "OKTA",
#             "profile": {
#                 "credentialId": "jane.doe@example.com",
#                 "deviceType": "SmartPhone_IPhone",
#                 "keys": [
#                     {
#                         "kty": "PKIX",
#                         "use": "sig",
#                         "kid": "default",
#                         "x5c": [
#                             "fdsfsdfsdfsd"
#                         ]
#                     }
#                 ],
#                 "name": "Jane.Doe iPhone",
#                 "platform": "IOS",
#                 "version": "10.2.1"
#             }
#         },
#         "policy": {
#             "allowRememberDevice": False,
#             "rememberDeviceLifetimeInMinutes": 0,
#             "rememberDeviceByDefault": False
#         },
#         "target": {
#             "type": "APP",
#             "name": "gimmecredstest",
#             "label": "Gimme-Creds-Test",
#             "_links": {
#                 "logo": {
#                     "name": "medium",
#                     "href": "https://op1static.oktacdn.com/bc/globalFileStoreRecord?id=gfsatgifysE8NG37F0h7",
#                     "type": "image/png"
#                 }
#             }
#         }
#     },
#     "_links": {
#         "next": {
#             "name": "poll",
#             "href": "https://example.okta.com/api/v1/authn/factors/opf9ei43pbAgb2qgc0h7/verify",
#             "hints": {
#                 "allow": [
#                     "POST"
#                 ]
#             }
#         },
#         "cancel": {
#             "href": "https://example.okta.com/api/v1/authn/cancel",
#             "hints": {
#                 "allow": [
#                     "POST"
#                 ]
#             }
#         },
#         "prev": {
#             "href": "https://example.okta.com/api/v1/authn/previous",
#             "hints": {
#                 "allow": [
#                     "POST"
#                 ]
#             }
#         },
#         "resend": [
#             {
#                 "name": "push",
#                 "href": "https://example.okta.com/api/v1/authn/factors/opf9ei43pbAgb2qgc0h7/verify/resend",
#                 "hints": {
#                     "allow": [
#                         "POST"
#                     ]
#                 }
#             }
#         ]
#     }
# }

#         responses.add(responses.POST, 'https://example.okta.com/api/v1/authn/factors/opf9ei43pbAgb2qgc0h7/verify', status=200, body=json.dumps(verify_response))
#         result = self.client._login_send_push(self.state_token, self.push_factor)
#         self.assertEqual(result, {'stateToken': self.state_token, 'apiResponse': verify_response})

#     @responses.activate
#     @patch('builtins.input', return_value='ann@example.com')
#     @patch('getpass.getpass', return_value='1234qwert')
#     @patch('gimme_aws_creds.webauthn.WebAuthnClient.make_credential', return_value=(b'', AttestationObject.create(
#         PackedAttestation.FORMAT, AuthenticatorData.create(
#             hashlib.sha256(b'example.okta.com').digest(),
#             AuthenticatorData.FLAG.USER_PRESENT | AuthenticatorData.FLAG.USER_VERIFIED | AuthenticatorData.FLAG.ATTESTED,
#             0, AttestedCredentialData.create(b'pasten-aag-uuid\0', b'pasten-credential-id', {3: -7})
#         ), {'alg': -7, 'sig': b'pasten-sig'}
#     )))
#     def test_authenticator_enrollment(self, mock_input, mock_password, mock_webauthn_client):
#         """ Tests a new webauthn authenticator enrollment """

#         setup_factors_response = """
# <!DOCTYPE html><html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
# <div id="subcontainer" class="sign-in-common sign-in">
#     <div id="password-verification-challenge" class="sign-in-content rounded-6">
#         <h1>Please verify your password</h1>
#         <div id="creds.edit" class="ajax-form-editor mfa-challenge-form margin-top-0"><form id="creds.edit.form" class="v-form large-text-inputs clearfix leave-open-on-success" action="/user/verify_password" method="post"><div style="display:none;" class="infobox infobox-error verify-error" id="creds.edit.errors">
#                     <span class="icon error-16"></span>
#                     <p>Please review the form to correct the following errors:</p>
#                     <ul class="bullets">
#                         <li><span id="creds.password.error"></span></li>
#                     </ul>
#                 </div>
#                 <input type="hidden" class="hide" name="_xsrfToken" id="_xsrfToken" value="f94a83d1c56414a0395d340605dd4f16214ed36faa318200ae9826ef98bef4ad"/><label id="creds.password.label" for="creds.password" class="first l-txt normal margin-btm clearfix icon-16" cssErrorClass="error">Password<input id="creds.password" name="password" class="margin-top-10 challenge" tabindex="0" type="password" value="" autocomplete="off"/></label><div class="clearfix clear">
#                     <input value="Verify" name="m-save" type="button" id="creds.button.submit" class="ajax-form-submit save button allow-in-read-only allow-in-safe-mode float-l ie7-offset" tabindex="3" onclick="trackEvent('MFA Challenge')"/></div>
#             </form></div></div>
# </div>
# </body>
# </html>
# """

#         second_factor_response = '''
# <!DOCTYPE html>
# <head>
# <title>Example, Inc - Extra Verification</title>
# </head>
# <body class="auth okta-container">
# <script type="text/javascript">function runLoginPage (fn) {var mainScript = document.createElement('script');mainScript.src = 'https://ok11static.oktacdn.com/assets/js/mvc/loginpage/initLoginPage.pack.88827f9bbcc5016901b032b2e26c64bf.js';mainScript.crossOrigin = 'anonymous';mainScript.integrity = 'sha384-vHr77eH+hWDyAa9aLN7uXxy3ek1uj1quPqidwdV8ljP3b4vpyZQZUtTOSmGQQOLR';document.getElementsByTagName('head')[0].appendChild(mainScript);fn && mainScript.addEventListener('load', function () { setTimeout(fn, 1) });}</script><script type="text/javascript">
# (function(){
#   var stateToken = '00Xg1Ci6KEli1338pWmP2gHUuYe0c_F4Nwd3fmoK9';
#   var authScheme = 'OAUTH2';
#   var webauthn = true;
# </body>
# </html>
# '''

#         auth_response = {
#             "stateToken": "00Wf8xZJ79mSoTYnJqXbvRegT8QB1EX1IBVk1TU7KI",
#             "type": "SESSION_STEP_UP",
#             "expiresAt": "2017-06-15T15:42:31.000Z",
#             "status": "SUCCESS",
#             "_embedded": {
#                 "user": {
#                     "id": "00u8cakq7vQwtK7sR0h7",
#                     "profile": {
#                         "login": "ann@example.com",
#                         "firstName": "Ann",
#                         "lastName": "Pasten",
#                         "locale": "en",
#                         "timeZone": "America/Los_Angeles"
#                     }
#                 },
#                 "target": {
#                     "type": "APP",
#                     "name": "gimmecredsserver",
#                     "label": "Gimme-Creds-Server (Dev)",
#                     "_links": {
#                         "logo": {
#                             "name": "medium",
#                             "href": "https://op1static.oktacdn.com/bc/globalFileStoreRecord?id=gfsatgifysE8NG37F0h7",
#                             "type": "image/png"
#                         }
#                     }
#                 }
#             },
#             "_links": {
#                 "next": {
#                     "name": "original",
#                     "href": "https://example.okta.com/login/step-up/redirect?stateToken=00Wf8xZJ79mSoTYnJqXbvRegT8QB1EX1IBVk1TU7KI",
#                     "hints": {
#                         "allow": [
#                             "GET"
#                         ]
#                     }
#                 }
#             }
#         }

#         setup_factor_response = '''
# <!DOCTYPE html>
# <head>
# <title>Example, Inc - Extra Verification</title>
# </head>
# <body class="auth okta-container">
# <script type="text/javascript">function runLoginPage (fn) {var mainScript = document.createElement('script');mainScript.src = 'https://ok11static.oktacdn.com/assets/js/mvc/loginpage/initLoginPage.pack.88827f9bbcc5016901b032b2e26c64bf.js';mainScript.crossOrigin = 'anonymous';mainScript.integrity = 'sha384-vHr77eH+hWDyAa9aLN7uXxy3ek1uj1quPqidwdV8ljP3b4vpyZQZUtTOSmGQQOLR';document.getElementsByTagName('head')[0].appendChild(mainScript);fn && mainScript.addEventListener('load', function () { setTimeout(fn, 1) });}</script><script type="text/javascript">
# (function(){
#   var stateToken = '13371Ci6KEli4Kopasten2gHUuYe0c_F4Nwd3fmoK9';
#   var authScheme = 'OAUTH2';
#   var webauthn = true;
# </body>
# </html>
# '''

#         introspect_response = {
#             "status": "MFA_ENROLL",
#             "_embedded": {
#                 "user": {
#                     "id": "13373h4rlzEuUlUOY4x6",
#                     "passwordChanged": "2020-04-01T06:01:15.000Z",
#                     "profile": {
#                         "login": "ann@example.com",
#                         "firstName": "Ann",
#                         "lastName": "Pasten",
#                         "locale": "en",
#                         "timeZone": "America/Los_Angeles"
#                     }
#                 },
#                 "factors": [
#                     {
#                         "factorType": "webauthn",
#                         "provider": "FIDO",
#                         "vendorName": "FIDO",
#                         "_links": {
#                             "enroll": {
#                                 "href": "https://example.okta.com/api/v1/authn/factors",
#                                 "hints": {
#                                     "allow": [
#                                         "POST"
#                                     ]
#                                 }
#                             }
#                         },
#                         "status": "NOT_SETUP",
#                         "enrollment": "OPTIONAL",
#                     }
#                 ]
#             },
#         }

#         enrollment_response = {
#             "stateToken": "13371Ci6KEli4Kopasten2gHUuYe0c_F4Nwd3fmoK9",
#             "status": "MFA_ENROLL_ACTIVATE",
#             "_embedded": {
#                 "user": {
#                     "id": "13373h4rlzEuUlUOY4x6",
#                     "profile": {
#                         "login": "ann@example.com",
#                         "firstName": "Ann",
#                         "lastName": "Pasten",
#                         "locale": "en",
#                         "timeZone": "America/Los_Angeles"
#                     }
#                 },
#                 "factor": {
#                     "id": "1337831cjAy4WtMOL4x6",
#                     "factorType": "webauthn",
#                     "provider": "FIDO",
#                     "vendorName": "FIDO",
#                     "_embedded": {
#                         "activation": {
#                             "rp": {
#                                 "name": "Example, Inc"
#                             },
#                             "user": {
#                                 "displayName": "Ann Pasten",
#                                 "name": "ann@example.com",
#                                 "id": "13373h4rlzEuUlUOY4x6"
#                             },
#                             "pubKeyCredParams": [
#                                 {
#                                     "type": "public-key",
#                                     "alg": -7
#                                 },
#                                 {
#                                     "type": "public-key",
#                                     "alg": -257
#                                 }
#                             ],
#                             "challenge": "QPABsCE0Xkbzlpqb6KbS",
#                             "attestation": "direct",
#                             "authenticatorSelection": {
#                                 "userVerification": "optional",
#                                 "requireResidentKey": False
#                             },
#                             "u2fParams": {
#                                 "appid": "https://example.okta.com"
#                             },
#                             "excludeCredentials": []
#                         }
#                     }
#                 }
#             },
#             "_links": {
#                 "next": {
#                     "name": "activate",
#                     "href": "https://example.okta.com/api/v1/authn/factors/1337831cjAy4WtMOL4x6/lifecycle/activate",
#                     "hints": {
#                         "allow": [
#                             "POST"
#                         ]
#                     }
#                 },
#             }
#         }

#         mfa_activation_response = {
#             "status": "SUCCESS",
#             "sessionToken": "13381WI0WOge2jey1crR6AnAkqfXZNUjoAgnWoGXU3WVaHN8dP7Pgln",
#             "_embedded": {
#                 "user": {
#                     "id": "13373h4rlzEuUlUOY4x6",
#                     "profile": {
#                         "login": "ann@example.com",
#                         "firstName": "Ann",
#                         "lastName": "Pasten",
#                         "locale": "en",
#                         "timeZone": "America/Los_Angeles"
#                     }
#                 }
#             }
#         }

#         setup_fido_webauthn_url = self.okta_org_url + '/user/settings/factors/setup?factorType=FIDO_WEBAUTHN'
#         verify_password_redirect_url = self.okta_org_url + '/user/verify_password?fromURI=%2Fenduser%2Fsettings'

#         # Request FIDO authenticator setup - get redirected to password verification
#         responses.add(responses.GET, setup_fido_webauthn_url, status=302,
#                       adding_headers={'Location': verify_password_redirect_url})
#         responses.add(responses.GET, verify_password_redirect_url, status=200, body=setup_factors_response)
#         responses.add(responses.POST, self.okta_org_url + '/user/verify_password', status=200)

#         # MFA for password verification
#         responses.add(responses.GET, self.okta_org_url + '/login/second-factor?fromURI=%2Fenduser%2Fsettings&'
#                                                          'forcePrompt=true&hideBgImage=true',
#                       status=200, body=second_factor_response)
#         responses.add(responses.POST, self.okta_org_url + '/api/v1/authn', status=200, body=json.dumps(auth_response))

#         # Continue FIDO authenticator setup once password re-verified
#         responses.add(responses.GET, setup_fido_webauthn_url, status=200, body=setup_factor_response)

#         # Introspect webauthn factors
#         responses.add(responses.POST, self.okta_org_url + '/api/v1/authn/introspect', status=200,
#                       body=json.dumps(introspect_response))

#         # Enroll & Activate new webauthn factor
#         responses.add(responses.POST, introspect_response['_embedded']['factors'][0]['_links']['enroll']['href'],
#                       status=200, body=json.dumps(enrollment_response))
#         responses.add(responses.POST, enrollment_response['_links']['next']['href'], status=200,
#                       body=json.dumps(mfa_activation_response))

#         # Finalize factor activation
#         enrollment_finalization_redirect_url = self.okta_org_url + '/enduser/settings?enrolledFactor=FIDO_WEBAUTHN'
#         enrollment_finalization_url = self.okta_org_url + '/login/sessionCookieRedirect?' \
#                                                           'checkAccountSetupComplete=true&token={session_token}&' \
#                                                           'redirectUrl={redirect_url}'.format(
#             session_token=mfa_activation_response['sessionToken'],
#             redirect_url=quote(enrollment_finalization_redirect_url))

#         responses.add(responses.GET, url=enrollment_finalization_url, status=302,
#                       adding_headers={'Location': enrollment_finalization_redirect_url})
#         responses.add(responses.GET, url=enrollment_finalization_redirect_url, status=200)

#         credential_id, user_name = self.client.setup_fido_authenticator()
#         assert credential_id == b'pasten-credential-id'
#         assert user_name == 'ann@example.com'

#     @responses.activate
#     def test_get_saml_response(self):
#         """Test that the SAML reponse was successful"""
#         responses.add(responses.GET, 'https://example.okta.com/app/gimmecreds/exkatg7u9g6LJfFrZ0h7/sso/saml', status=200, body=self.login_saml)
#         result = self.client.get_saml_response('https://example.okta.com/app/gimmecreds/exkatg7u9g6LJfFrZ0h7/sso/saml')
#         self.assertEqual(result['TargetUrl'], 'https://localhost:8443/saml/SSO')

#     @responses.activate
#     def test_missing_saml_response(self):
#         """Test that the SAML reponse was successful (failed)"""
#         responses.add(responses.GET, 'https://example.okta.com/app/gimmecreds/exkatg7u9g6LJfFrZ0h7/sso/saml', status=200, body="")
#         with self.assertRaises(RuntimeError):
#             result = self.client.get_saml_response('https://example.okta.com/app/gimmecreds/exkatg7u9g6LJfFrZ0h7/sso/saml')

#     # @responses.activate
#     # def test_get_aws_account_info(self):
#     #     """Test the gimme_creds_server response"""
#     #     responses.add(responses.POST, 'https://localhost:8443/saml/SSO', status=200)
#     #     responses.add(responses.GET, self.gimme_creds_server + '/api/v1/accounts', status=200, body=json.dumps(self.api_results))
#     #     # The SAMLResponse value doesn't matter because the API response is mocked
#     #     saml_data = {'SAMLResponse': 'BASE64_String', 'RelayState': '', 'TargetUrl': 'https://localhost:8443/saml/SSO'}
#     #     result = self.client._get_aws_account_info(self.gimme_creds_server, saml_data)
#     #     self.assertEqual(self.client.aws_access, self.api_results)

#     @patch('builtins.input', return_value='0')
#     def test_choose_factor_sms(self, mock_input):
#         """ Test selecting SMS as a MFA"""
#         result = self.client._choose_factor(self.factor_list)
#         self.assertEqual(result, self.sms_factor)

#     @patch('builtins.input', return_value='1')
#     def test_choose_factor_push(self, mock_input):
#         """ Test selecting Okta Verify as a MFA"""
#         result = self.client._choose_factor(self.factor_list)
#         self.assertEqual(result, self.push_factor)

#     @patch('builtins.input', return_value='2')
#     def test_choose_factor_totp(self, mock_input):
#         """ Test selecting TOTP code as a MFA"""
#         result = self.client._choose_factor(self.factor_list)
#         self.assertEqual(result, self.totp_factor)

#     @patch('builtins.input', return_value='12')
#     def test_choose_bad_factor_totp(self, mock_input):
#         """ Test selecting an invalid MFA factor"""
#         with self.assertRaises(errors.GimmeAWSCredsExitBase):
#             result = self.client._choose_factor(self.factor_list)

#     @patch('builtins.input', return_value='3')
#     def test_choose_factor_webauthn(self, mock_input):
#         """ Test selecting webauthn code as a MFA"""
#         result = self.client._choose_factor(self.factor_list)
#         self.assertEqual(result, self.webauthn_factor)

#     @patch('builtins.input', return_value='a')
#     def test_choose_non_number_factor_totp(self, mock_input):
#         """ Test entering a non number value as MFA factor"""
#         with self.assertRaises(errors.GimmeAWSCredsExitBase):
#             result = self.client._choose_factor(self.factor_list)

#     def test_build_factor_name_sms(self):
#         """ Test building a display name for SMS"""
#         result = self.client._build_factor_name(self.sms_factor)
#         self.assertEqual(result, "sms: +1 XXX-XXX-1234")

#     def test_build_factor_name_push(self):
#         """ Test building a display name for push"""
#         result = self.client._build_factor_name(self.push_factor)
#         self.assertEqual(result, "Okta Verify App: SmartPhone_IPhone: Jane.Doe iPhone")

#     def test_build_factor_name_totp(self):
#         """ Test building a display name for TOTP"""
#         result = self.client._build_factor_name(self.totp_factor)
#         self.assertEqual(result, "token:software:totp( OKTA ) : jane.doe@example.com")

#     def test_build_factor_name_hardware(self):
#         """ Test building a display name for hardware"""
#         result = self.client._build_factor_name(self.hardware_factor)
#         self.assertEqual(result, "token:hardware: YUBICO")

#     def test_build_factor_name_unknown(self):
#         """ Handle an unknown MFA factor"""
#         with self.captured_output() as (out, err):
#             result = self.client._build_factor_name(self.unknown_factor)
#             self.assertEqual(result, "Unknown MFA type: UNKNOWN_FACTOR")

#     def test_build_factor_name_webauthn_unregistered(self):
#         """ Test building a display name for an unregistered webauthn factor """
#         result = self.client._build_factor_name(self.webauthn_factor)
#         self.assertEqual(result, "webauthn: webauthn")

#     def test_build_factor_name_webauthn_unregistered_with_authenticator_name(self):
#         """ Test building a display name for an unregistered webauthn factor with a specified authenticator name """
#         webauthn_factor_with_authenticator_name = self.webauthn_factor.copy()

#         authenticator_name = 'Pasten Authenticator'
#         webauthn_factor_with_authenticator_name['profile']['authenticatorName'] = authenticator_name

#         result = self.client._build_factor_name(self.webauthn_factor)
#         self.assertEqual(result, "webauthn: " + authenticator_name)

#     @patch('gimme_aws_creds.registered_authenticators.RegisteredAuthenticators.get_authenticator_user',
#            return_value='jane.doe@example.com')
#     def test_build_factor_name_webauthn_registered(self, mock_input):
#         """ Test building a display name for a registered webauthn factor """
#         result = self.client._build_factor_name(self.webauthn_factor)
#         self.assertEqual(result, "webauthn: jane.doe@example.com")

#     # def test_get_app_by_name(self):
#     #     """ Test selecting app by name"""
#     #     self.client.aws_access = self.api_results
#     #     result = self.client.get_app_by_name('Sample AWS Account')
#     #     self.assertEqual(result['name'], 'Sample AWS Account')
#     #
#     # def test_get_role_by_name(self):
#     #     """ Test selecting app by name"""
#     #     self.client.aws_access = self.api_results
#     #     result = self.client.get_role_by_name(self.api_results[0], 'ReadOnly')
#     #     self.assertEqual(result['name'], 'ReadOnly')

#     # @patch('builtins.input', return_value='0')
#     # def test_choose_role(self, mock_input):
#     #     """ Test selecting role with user input"""
#     #     result = self.client.choose_role(self.api_results[0])
#     #     self.assertEqual(result['name'], 'ReadOnly')
#     #
#     # @patch('builtins.input', return_value='0')
#     # def test_choose_app(self, mock_input):
#     #     """ Test selecting app with user input"""
#     #     self.client.aws_access = self.api_results
#     #     result = self.client.choose_app()
#     #     self.assertEqual(result['name'], 'Sample AWS Account')
